menu:
    Blog: /
    Archive: /archives/
    # Weibo: 
    GitHub: https://github.com/andyccc
    # Rss: /atom.xml

favicon: /favicon.jpeg
logo: /favicon.jpeg

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
